# syntax=docker/dockerfile:1
ARG CUDA=12.9.1
ARG UBUNTU=24.04
FROM nvidia/cuda:${CUDA}-devel-ubuntu${UBUNTU} AS base

# install dependencies
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean && \
    echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' \
        > /etc/apt/apt.conf.d/keep-cache && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get update --yes && \
    apt-get upgrade --yes --no-install-recommends && \
    apt-get install --yes --no-install-recommends \
        # basic dependencies
        git \
        curl \
        cmake \
        ninja-build \
        clang \
        pkg-config \
        # g2o dependencies
        libatlas-base-dev \
        libsuitesparse-dev \
        # backward-cpp dependencies
        binutils-dev \
        # stella-vslam dependencies
        libomp-dev \
        libopencv-dev \
        libeigen3-dev \
        libyaml-cpp-dev \
        libsqlite3-dev \
        # python dependencies
        python3 \
        python3-pip \
        python3-opencv \
        python3-msgpack \
        python3-numpy \
        python3-scipy \
        # python dev dependencies
        python3-dev \
        pybind11-dev \
        && \
    pip install --no-cache-dir --break-system-packages \
        # build dependencies
        pybind11-stubgen \
        # runtime dependencies
        numba \
        # 1.0.25 - 1.0.26 fail to render line segments propperly
        viser==1.0.24

# compile settings
ENV C=clang CXX=clang++
ARG NUM_THREADS=0
WORKDIR /tmp

# g2o
ARG G2O_VERSION=20241228_git
RUN git clone https://github.com/RainerKuemmerle/g2o.git --branch ${G2O_VERSION} --depth 1 && \
    cd g2o && \
    cmake -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_SHARED_LIBS=ON \
        -DBUILD_UNITTESTS=OFF \
        -DG2O_USE_CHOLMOD=OFF \
        -DG2O_USE_CSPARSE=ON \
        -DG2O_USE_OPENGL=OFF \
        -DG2O_USE_OPENMP=OFF \
        -DG2O_BUILD_APPS=OFF \
        -DG2O_BUILD_EXAMPLES=OFF \
        -DG2O_BUILD_LINKED_APPS=OFF \
        && \
    cmake --build build --parallel $(test ${NUM_THREADS} -eq 0 && nproc || (printf ${NUM_THREADS})) && \
    cmake --install build && \
    rm -rf /tmp/g2o

# backward-cpp
ARG BACKWARD_CPP_COMMIT=5ffb2c879ebdbea3bdb8477c671e32b1c984beaa
RUN git clone https://github.com/bombela/backward-cpp.git && \
    cd backward-cpp && \
    git checkout ${BACKWARD_CPP_COMMIT} && \
    cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release && \
    cmake --build build --parallel $(test ${NUM_THREADS} -eq 0 && nproc || (printf ${NUM_THREADS})) && \
    cmake --install build && \
    rm -rf /tmp/backward-cpp


FROM base AS build

# stella
COPY --exclude=tools --exclude=example . /stella
RUN cd /stella && \
    export PYTHONPATH=/stella/build/lib && \
    cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release && \
    cmake --build build --parallel $(test ${NUM_THREADS} -eq 0 && nproc || (printf ${NUM_THREADS})) && \
    cmake --install build && \
    rm -rf build


FROM base AS devel

# install dev dependencies
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get update --yes && \
    apt-get install --yes --no-install-recommends \
        # dev tools
        clang-tidy \
        clang-format \
        clangd \
        # cli tools
        sqlite3 \
        # sudo setup
        sudo && \
    echo "ubuntu ALL=(ALL) NOPASSWD:ALL" | install -m 0440 /dev/stdin /etc/sudoers.d/ubuntu


FROM nvidia/cuda:${CUDA}-runtime-ubuntu${UBUNTU} AS runtime

# install runtime dependencies
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean && \
    echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' \
        > /etc/apt/apt.conf.d/keep-cache && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get update --yes && \
    apt-get upgrade --yes --no-install-recommends && \
    apt-get install --yes --no-install-recommends \
        # shared libraries
        libatlas3-base \
        libcxsparse4 \
        libyaml-cpp0.8 \
        libamd3 \
        libcamd3 \
        libcolamd3 \
        libccolamd3 \
        libomp5 \
        # python packages
        python3 \
        python3-opencv \
        python3-msgpack \
        python3-numpy \
        python3-scipy

# copy build artifacts
COPY --from=build --exclude=cmake --exclude=pybind11* /usr/local/lib /usr/local/lib/
RUN ldconfig

# setup runtime environment
COPY --parents tools example /stella/
WORKDIR /stella/tools
USER ubuntu
EXPOSE 8080/tcp
CMD [ "/bin/bash", "-c", "echo 'Available StellaVSLAM tools:'; find . -maxdepth 1 -type f -executable -printf '   %p\\n' | sort; exec /bin/bash" ]
